articles_collected = 'https://drive.google.com/drive/u/0/folders/1jG1UdiypUcorbSMGV_ey5gB9rptI_4Lk'
plot1 = 'https://www.desmos.com/calculator/thn8me1jlu'
plot2 = 'https://www.desmos.com/calculator/gfhjc3eek2'
plot3 = 'https://www.desmos.com/calculator/vtrizlbyig'